WINDY Your friendly file sorteer

[] Finish Windy bot
[] Make a cross-platform/os for windy(e.g. Windows,OSX etc...)
[] Create a way to config windy
[] Clean up and expand
[] Make a pip repo

\\Clean up
\\Add a way to move other files to directory
\\Make a separate folder for the extensions directories
\\Create a tmp file
\\rework everything move from downloads to out downloads_folder
\\Make a function to add file extensions with command_line options
\\Make Windy package
